export {
  sliders,
  announcements,
  institutionProfile,
  managers,
  visionMission,
  educationPrograms,
  facilities,
  achievements,
  servicePoints,
  agendas,
  newsCategories,
  news,
  tutors,
  students,
  downloads,
  products,
  alumni,
  gallery,
  elearningCourses,
  elearningSessions,
  elearningMaterials,
  elearningEvaluations,
  elearningSetups,
} from "../db/schema";
